### PR TITLE
better order mapping

### PR DESCRIPTION
**Pull request by norgeindian**
This pull request ensures:
- If the order number and the amount match, the order is mapped as "certain".
- If the invoice number and the amount match, the order is mapped as "certain".
- If just the order number or the invoice number match, the order is mapped as "guessed".
- If just the amount matches, the order is mapped as "guessed".

### CODE REVIEW

**Comment by sprankhub** [comment]
:+1:  This is much better!

**Comment by Kinento** [comment]
Thank you for the improvements.
I am willing to accept the changes if you fix the following two points:
1. You removed support for Banco Monex, a bank you probably don't support. However, other users might use it. Could you re-add it?
2. You use spacing for indentation. Although that would have been a better solution from the start, this change is not about the indentation. Could you change it back to tabs? This way it is very confusing for me (and GitHub) to see what has actually changed.

**Comment by sprankhub** [comment]
1. We of course could not test it, but we kept the Banco Monex code: https://github.com/norgeindian/bank-integration/blob/d5adce50d457f7bfaf3fbf0561e32a49906b99e6/app/code/community/Kinento/Bankintegration/Model/Bankintegration.php#L1093
2. Commit follows.

Would you accept a PR which formats the extension in Magento standard?

**Comment by Kinento** [comment]
The modules was created way back in 2009, so you'll have to explain me what you mean with the "Magento standard"?

**Comment by sprankhub** [comment]
Thanks for merging!

I would like to change the code style to the Magento standard, which is afaik the Zend standard.

**Comment by Kinento** [comment]
OK, I'm still not sure what that would mean in practise. In any case, I agree that some things are not done the Magento way and many things can be improved from a software engineering perspective.

I am happy to merge your contributions. But perhaps you'd like that I transfer ownership in some way to you? As you can read in the README file, Kinento has done commercial activities from 2009 until the end of 2014. In 2015, the only contributions which can be expected by Kinento are bug fixes for customers who purchased this module last year. If you would like to maintain, extend, or even commercialise a version of this module, please let me know!

**Pull request merged**
